module.exports = {
  preset: 'react-native',
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
  testEnvironment: 'node',
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json'],
  testMatch: ['**/__tests__/**/*.(ts|tsx|js)', '**/*.(test|spec).(ts|tsx|js)'],
  collectCoverageFrom: [
    'src/**/*.{ts,tsx,js,jsx}',
    '!src/**/*.d.ts',
    '!src/**/index.ts',
    '!src/**/*.stories.{ts,tsx}',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'html'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@app/(.*)$': '<rootDir>/src/App/$1',
    '^@assets/(.*)$': '<rootDir>/assets/$1',
    '^@config/(.*)$': '<rootDir>/src/config/$1',
    '^@i18n/(.*)$': '<rootDir>/src/config/i18n/$1',
    '^@context/(.*)$': '<rootDir>/src/context/$1',
    '^@hooks/(.*)$': '<rootDir>/src/hooks/$1',
    '^@navigation/(.*)$': '<rootDir>/src/navigation/$1',
    '^@networking/(.*)$': '<rootDir>/src/networking/$1',
    '^@themes/(.*)$': '<rootDir>/src/themes/$1',
    '^@redux/(.*)$': '<rootDir>/src/redux/$1',
    '^@slices/(.*)$': '<rootDir>/src/redux/slices/$1',
    '^@components/(.*)$': '<rootDir>/src/ui/components/$1',
    '^@screens/(.*)$': '<rootDir>/src/ui/screens/$1',
    '^@validations/(.*)$': '<rootDir>/src/validations/$1',
    '^@api/(.*)$': '<rootDir>/src/api/$1',
    '^@models/(.*)$': '<rootDir>/src/models/$1',
    '^@utils/(.*)$': '<rootDir>/src/utils/$1',
  },
  transformIgnorePatterns: [
    'node_modules/(?!(react-native|@react-native|@react-navigation|expo|@expo|react-native-vector-icons|react-native-svg|react-native-reanimated|react-native-gesture-handler|react-native-screens|react-native-safe-area-context|@react-native-async-storage|react-native-calendars|react-native-date-picker|react-native-modal-datetime-picker|react-native-toast-notifications|react-native-localize)/)',
  ],
  globals: {
    __DEV__: true,
  },
};
